apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/microservicios-nest/image-registry/payments-ms
        name: payments-ms
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:3000/api/payments/success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:3000/api/payments/cancel"
          - name: STRIPE_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secret
                key: STRIPE_SECRET
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secret
                key: STRIPE_ENDPOINT_SECRET
        resources: {}
status: {}